# Generated by Django 5.1.5 on 2025-01-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_receptionist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='branch',
        ),
    ]
